defaults:
  - generator: bigbigan

# Generate GAN-generated images on-the-fly during training 
load_from_disk: False

# Options for generation process
gan_val_num_images: 256
gan_val_file: "/tmp/gan-seg/gan-val-samples.pth"
regenerate_gan_val_file: True
save_gan_val_vis: True

# Training options
iters_per_epoch: 2000

# GAN Dataset
device: 'cuda'  # device for generator
model_type: "fixed"
checkpoint: null  # model checkpoint (e.g. .../latest.pth)
zs: null  # path to .pny file (e.g. .../BigBiGAN_ImageNet_z.npy)
kwargs:
  z_noise: 0.0
  z_noise_truncation: 1.0
  r: 5.0  # radius of latent shift
  filter_cc_threshold: 0.2
  filter_size_thresholds: [0.0, 0.5]
  filter_histogram_bins: 12 
  filter_roundness_threshold: 0.0
  invert: False
  batch_size: 95
  generation_batch_size: 95

# Options generating dataset and saving to disk 
save_dir: null
save_size: null
offset: 0